app.version=@project.version@
spring.profiles.active=dev
server.error.include-message=always
server.port=9090
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.main.allow-circular-references=true

########################### Database Properties ###############################
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=asshofa
spring.datasource.password=asshofa@123
spring.datasource.driver-class-name=org.postgresql.Driver

############################ MyBatis Properties ################################
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.mapper-locations=classpath:**/mapper/*.xml

############################ JWT Properties ################################
security.jwt.secret-key=g8blurVE7c8d7KsLRdRWWPx20CBRD9BiSumJbFrkNMVIVJOttLowq2nnkTaB2R7I99mz40kU8CEHFfc5pWxM20X5L6nEZNWnrPXPVa8Jpy1DXBLuZKEhzRXTtMHyYEto89FwYkBIpjyqCBOTYdgQdwmKUNaABSm0hQVJvUnbHXRbpU80nPLi9xUN4CQ41r0a0Qc3aKbPdz9Xk4nzcFRe0hr0oOjSn97a4uPwHSRRmlhKTQvBBUa8EA5jhO7sOhtO1NOOikpVr4VFjd0Mx8i3TvQ4Osl14x6gxeBBcThjMxDkUdGp2NEDEAxP9UWQn29c5JTSv90Ag8blurVE7c8d7KsLRdRWWPx20CBRD9BiSumJbFrkNMVIVJOttLowq2nnkTaB2R7I99mz40kU8CEHFfc5pWxM20X5L6nEZNWnrPXPVa8Jpy1DXBLuZKEhzRXTtMHyYEto89FwYkBIpjyqCBOTYdgQdwmKUNaABSm0hQVJvUnbHXRbpU80nPLi9xUN4CQ41r0a0Qc3aKbPdz9Xk4nzcFRe0hr0oOjSn97a4uPwHSRRmlhKTQvBBUa8EA5jhO7sOhtO1NOOikpVr4VFjd0Mx8i3TvQ4Osl14x6gxeBBcThjMxDkUdGp2NEDEAxP9UWQn29c5JTSv90A
security.jwt.expirationtime=180000

logging.level.com.asshofa=DEBUG
